global:
  scrape_interval: 15s       # 15초마다 스크레이프
  evaluation_interval: 15s

scrape_configs:
  - job_name: "opswatch"
    scheme: https                                    # Render는 HTTPS
    static_configs:
      - targets: ["opswatch-ml-service.onrender.com"]      # Render 운영 서버
    metrics_path: /metrics
